[package]
name = "sdl"
version = "0.1.0"
authors = ["karl.runge <karl.runge@defendtex.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 =      "0.34.0"
sdl2-sys =  "0.34.0"
gl =        "0.14.0"